### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by MarianSijanin** [Zachac/Tweego-File-Splitter#2]
Not sure is it a bug or not. 
But I had issues because my Python 3 default encoding wasn't utf-8 (like most .twee files, I suppose). 
So I changed both "open" calls to specify "encoding="utf-8"" (lines 30 and 36) and it helped.

**Comment by Zachac** [comment]
Could you expand on what errors you were getting. Like whether or not Python was throwing an error or if it was tweego, or both.

**Comment by MarianSijanin** [comment]
It was Python throwing an error:
```
q:\temp>python tweego_file_splitter.py 1.twee src
Traceback (most recent call last):
  File "tweego_file_splitter.py", line 64, in <module>
    splitFile(file, directory)
  File "tweego_file_splitter.py", line 37, in splitFile
    content = f.read()
  File "C:\Users\****\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 611429: character maps to <undefined>
```
